//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitapShop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KitapShop.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string ad {
            get {
                return ResourceManager.GetString("ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınızı Giriniz.
        /// </summary>
        public static string adplace {
            get {
                return ResourceManager.GetString("adplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Dilinizi Seçiniz!.
        /// </summary>
        public static string dilsec {
            get {
                return ResourceManager.GetString("dilsec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10&apos;dan fazla yeni veya ikinci el kitap.
        /// </summary>
        public static string hak1 {
            get {
                return ResourceManager.GetString("hak1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni çıkan kitaplardan aklınızda ne varsa KitapShop&apos;da bulabilirsiniz..
        /// </summary>
        public static string hak2 {
            get {
                return ResourceManager.GetString("hak2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenle alın, güvenle alışveriş yapın!.
        /// </summary>
        public static string hak3 {
            get {
                return ResourceManager.GetString("hak3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burada tüm alışverişleriniz KitapShop&apos;un %100 güvencesi altında gerçekleşir..
        /// </summary>
        public static string hak4 {
            get {
                return ResourceManager.GetString("hak4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her gün 100&apos;lerce yeni fırsatı yakalayın.
        /// </summary>
        public static string hak5 {
            get {
                return ResourceManager.GetString("hak5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özenle seçtiğimiz, %70&apos;e varan indirimlerle satılan kitapları Mağaza&apos;da bulabilirsiniz..
        /// </summary>
        public static string hak6 {
            get {
                return ResourceManager.GetString("hak6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kendi mağazanızı açın, işinizi büyütün.
        /// </summary>
        public static string hak7 {
            get {
                return ResourceManager.GetString("hak7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KitapShopta her 3 saniyede 1 ürün satılıyor.
        /// </summary>
        public static string hak8 {
            get {
                return ResourceManager.GetString("hak8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlgi alanınıza göre farklı kategorilerde hayatınıza ve alışverişinize rehber olacak içerikler KitapShop.com&apos;da..
        /// </summary>
        public static string hak9 {
            get {
                return ResourceManager.GetString("hak9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KitapShop&apos;un Fırsatlarla Dolu Renkli Dünyasına Hoş Geldiniz!.
        /// </summary>
        public static string hakbas {
            get {
                return ResourceManager.GetString("hakbas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string hakkimizda {
            get {
                return ResourceManager.GetString("hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iletisim.
        /// </summary>
        public static string iletisim {
            get {
                return ResourceManager.GetString("iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANASAYFA.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoğraf.
        /// </summary>
        public static string kayitfoto {
            get {
                return ResourceManager.GetString("kayitfoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onayla.
        /// </summary>
        public static string kayitol {
            get {
                return ResourceManager.GetString("kayitol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magaza.
        /// </summary>
        public static string Magaza {
            get {
                return ResourceManager.GetString("Magaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailinizi Giriniz.
        /// </summary>
        public static string mailplace {
            get {
                return ResourceManager.GetString("mailplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string nick {
            get {
                return ResourceManager.GetString("nick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı Giriniz.
        /// </summary>
        public static string nickplace {
            get {
                return ResourceManager.GetString("nickplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        public static string parola {
            get {
                return ResourceManager.GetString("parola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola Giriniz.
        /// </summary>
        public static string parolaplace {
            get {
                return ResourceManager.GetString("parolaplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string soyad {
            get {
                return ResourceManager.GetString("soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadınızı Giriniz.
        /// </summary>
        public static string soyadplace {
            get {
                return ResourceManager.GetString("soyadplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.. ... .. .. .
        /// </summary>
        public static string telplace {
            get {
                return ResourceManager.GetString("telplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ücretsiz Kayıt Olun.
        /// </summary>
        public static string ucretsiz {
            get {
                return ResourceManager.GetString("ucretsiz", resourceCulture);
            }
        }
    }
}
